### PR TITLE
Node12fix

### PR DESCRIPTION
**Pull request by Andersbakken**
Posix doesn't compile in newer nodejs versions (>= 11 I think).

This patch fixes it by using more Nan:: methods.

### CODE REVIEW

**Comment by davidlehn** [comment]
Ping.  It would be nice to get this released.  I'd also suggest adding an explicit version "12" to .travis.yml.

**Comment by ankursachdeva11** [comment]
@davidlehn , I have tested npm install in v12.14.0 using your changes but I am getting an error while installing posix. 
@Andersbakken @davidlehn , Please check and let us know, how can we support posix for node v12.

**Comment by ankursachdeva11** [comment]
Please merge this PR.

**Comment by ankursachdeva11** [comment]
@davidlehn @Andersbakken @melor, Please merge this PR. I have tested changes. We need this new release contains v12 changes.

**Comment by ankursachdeva11** [comment]
@melor , 
Thanks for merging this.
please create a new release version.

**Comment by ankursachdeva11** [comment]
@melor , Thanks for merging this.

Please create a new release version tag. So that we can use latest code in our application.

**Pull request merged**
