### PR TITLE
upgrade nan.

### PR DESCRIPTION
**Pull request by robey**
this allows posix to work with recent versions of node/iojs.

### CODE REVIEW

**Comment by melor** [comment]
Thanks for the patch. There are some SIGSEGV issues with node 0.8 and 0.10 with these changes: at least setsid and setreuid tests crash on those versions when setting up an ErrnoException. I see nothing obvious in the code...

https://travis-ci.org/ohmu/node-posix/jobs/78421507
https://travis-ci.org/ohmu/node-posix/jobs/78424672

My branch for valgrinding the tests in travis (don't have old node.js version handy): https://github.com/ohmu/node-posix/tree/upgrade_nan

**Comment by robey** [comment]
I think I figured this out. It looks fine on Darwin, but on Linux, under node 10, the third argument ("message") to `NanErrnoException` is apparently not optional. Setting it explicitly to `""` everywhere stops the segfault.

**Comment by robey** [comment]
I can't figure out how to reproduce the iojs v3.3.0 failure. It works for me on Linux & Darwin. But the failure on Travis is total and immediate (it can't even compile the C++ code), so I'm stumped on that one.

**Comment by melor** [comment]
All tests pass in travis. Merged, thanks a lot!

**Pull request closed without merging**
